### ISSUE TITLE
是否有安装编译教程

### ISSUE THREAD

**Issue by fslit** [lindb/lindb#121]
对GO还不是很了解，想安装使用LINDB，是否有安装教程学习

**Comment by CodingCrush** [comment]
目前lindb和lindb.io的网站还未开发完成，这个月会release个alpha版本，后面在 lindb.io 会有详细介绍。也会提供编译好的二进制包

**Comment by fslit** [comment]
感谢回复，我们很关注这个项目，希望能够超越infuxdb

**Comment by fslit** [comment]
该项目是否有商业技术服务支持

**Comment by CodingCrush** [comment]
@fslit 目前还没有这个计划，后面可以通过qq或微信群交流

**Comment by 2892931976** [comment]
有交流群吗？

**Comment by ghsobetter** [comment]
最近领导让我调研这个服务 , 然而我还没接触过go的项目

**Comment by ghsobetter** [comment]
> 对GO还不是很了解，想安装使用LINDB，是否有安装教程学习

你现在会使用了吗? 我现在有相同的困扰

**Comment by stone1100** [comment]
目前还在开发第一个版本，完了会有完善的编译安装说明

**Comment by CodingCrush** [comment]
> 最近领导让我调研这个服务 , 然而我还没接触过go的项目

还要一段时间才能完成开发，go版很多细节都经过重新设计，和现在公司内部用的Java版存在差异，所以开发工作量比较大。完成后会放出文档，可以直接通过二进制包使用

**Comment by ghsobetter** [comment]
> 目前还在开发第一个版本，完了会有完善的编译安装说明
老师你能加下我的微信不? 我最近领导让研究这个, 我准备先把知乎里面那个文章弄清楚再来看看这个项目

**Comment by ghsobetter** [comment]
> 目前还在开发第一个版本，完了会有完善的编译安装说明

我的微信ghbetter

**Comment by CodingCrush** [comment]
> > 目前还在开发第一个版本，完了会有完善的编译安装说明
> 
> 我的微信ghbetter

![mmqrcode1565358542908](https://user-images.githubusercontent.com/21290558/62783947-f6ad1880-baef-11e9-80a1-427ffcd60c59.png)

**Comment by hanlizhihao** [comment]
> > > 目前还在开发第一个版本，完了会有完善的编译安装说明
> > 
> > 
> > 我的微信ghbetter
> 
> ![mmqrcode1565358542908](https://user-images.githubusercontent.com/21290558/62783947-f6ad1880-baef-11e9-80a1-427ffcd60c59.png)

连接都失效了，已加您微信，希望能通过以下
请教您一个问题，文档描述LinDB 使用了基于 Series(Tags) 的 sharding 策略，我看代码基于timeSeriesStore存储series，代码中对同一个指标的不同series进行了分组，但一个指标的所有series应该还在一个节点上，不是不同series在不同节点，不知道我看的对不对，辛苦大神帮忙解答一下，请问lindb是怎么进行series分片的呢?

**Comment by stone1100** [comment]
- sharding 是在 broker 写 wal 的时候已经做好了，每个 shard 的一个 wal, 然后每个 shard 的 wal 会复制到对应 storage node 的 memory database 中，time series store 是 memory database 存储 series 部分；
- memory database 是 shard level 的，每个 storage node 都会有；

**Comment by lichong2005** [comment]
> > 最近领导让我调研这个服务 , 然而我还没接触过go的项目
> 
> 还要一段时间才能完成开发，go版很多细节都经过重新设计，和现在公司内部用的Java版存在差异，所以开发工作量比较大。完成后会放出文档，可以直接通过二进制包使用

您好，本人对Go不太了解，有个疑惑：为何用Go重新实现一遍，不直接开源Java版？Java版除了商业隐私上的考量，是否在性能上，或者功能上有不足的吗？

**Comment by stone1100** [comment]
> > > 最近领导让我调研这个服务 , 然而我还没接触过go的项目
> > 
> > 
> > 还要一段时间才能完成开发，go版很多细节都经过重新设计，和现在公司内部用的Java版存在差异，所以开发工作量比较大。完成后会放出文档，可以直接通过二进制包使用
> 
> 您好，本人对Go不太了解，有个疑惑：为何用Go重新实现一遍，不直接开源Java版？Java版除了商业隐私上的考量，是否在性能上，或者功能上有不足的吗？

- Java版本的部分组件耦合在别的组件里面
- Index放在RocksDB里面，也存在一定的问题
- 自研的LSM结构，其实在时序场景会有一定的问题
- 开源版本希望能成为一个体系，包括新增自研Index及MemoryDB+Persistent DB
- 能将计算和存储分离
- 希望通过Goroutine有加大查询的并发

基于原来的架构调整还是很大的，所以选择了Rebuild或者不是Refactor
