### ISSUE TITLE
Request an explanation for project name

### ISSUE THREAD

**Issue by zhxxch** [lindb/lindb#127]
请问["LinDB("Lin" stands for wisdom in Shanghainese)"](https://git.io/fjQgu)是否表明此项目受到了上海市政府支持或财政资助？如果不是，希望此项目不再包含地域性指向。

如果作者看到别的开源软件声称其名字的含义是“美国人的智慧”“北京人的智慧”“海淀人的智慧”难道不会认为这样太自负了吗？

作者若称此项目是wisdom in ELEME那自然无可指摘，因为ELEME为本项目的产生创造了条件、提供了便利，是利益共同体。但作者把“上海人的智慧”捆绑进来，我认为作者需要解释一下，为什么把上海人的智慧和其他地区人民的智慧区别开？为什么冠上“上海”的名字？我能想到的唯一可能就是此项目和上海市政府有关。涉及行政区的名称，一定是名副其实，或者体现国家意志（比如军舰）。

如果作者认为我在抬杠，我只能说如果想抬杠我会推动其他项目以“朝阳人的智慧”命名，并来这里讲上海人的智慧不如朝阳人的智慧。

我很抱歉这个issue比较政治化，希望作者注意到：为项目起名字时不要令人有地方主义的联想。

**Comment by CodingCrush** [comment]
这个单词只是 “上海话” 的意思， 和上海人没关系。

**Comment by zhxxch** [comment]
不过这个误会已经有了……请见：
https://gitee.com/mirrors/LinDB

**Comment by CodingCrush** [comment]
明白了，那个是机翻的。。。

**Comment by stone1100** [comment]
我们调整一下，感谢你的反馈

**Comment by zhxxch** [comment]
那句话我感觉确实有歧义，哎呀……我不懂上海话，要是wisdom周围有个引号我也不会费劲写最上面一段话了（结果搞得像我自己以小人之心度君子之腹），好吧，可能我的中文和英文水平都有待提高。最后：用英文解释这个中文的梗，目前的措辞我估计只有中国人才能看懂（而且我一中国人还没看懂= =）。

**Comment by stone1100** [comment]
是我们考虑的不够周全，下午就会调整说明描述，避免再引起不必会的误会

**Comment by tevino** [comment]
It should be described as:
> `Lin` stands for the pronunciation of `灵` in Shanghai dialect which means effective. 



[Here](https://github.com/lindb/lindb/pull/128) I removed it to avoid further misunderstanding.
