### ISSUE TITLE
Propose: no prefix in EVERY SINGLE commit message

### ISSUE THREAD

**Issue by tevino** [lindb/lindb#132]
I'm trying not to be a picky jerk here.

## What
What I'm talking about here is the requirement described in the [contributing guideline](https://github.com/lindb/lindb/blob/develop/CONTRIBUTING.md#format) to add a prefix to commit messages.

That's `[type:#issue][scope]: subject` for every single commit.

## Why

Yes, I can see the pros of it and I'm totally fine with the format, however the `every single commit` part doesn't sound necessary, here are the cons IMHO:

- The available length for the real message reduced a lot(44%)
    - e.g. `[type:#issue][scope]: ` takes **22** characters away from **50** in total.
- It's a burden for one to make multiple commits
- A PR usually, if not necessarily involves **one single** feature, the prefix of commit messages within the same PR will be very much alike, if not exact.
    - Most PRs merged so far contains only one single commit, is it a compromise of the guideline?
- Issues exist only on GitHub, the numbers make no sense immediately if the project migrate to another platform, imagine a lot of links to an abandoned Gitlab in the existing commit history for example

## Suggestion

How about we keep the GitHub stuff on GitHub instead of in the commit history, the title of a PR is a good place, even the commit message of the merge is reasonable.

---

Feel free to close.

**Comment by CodingCrush** [comment]
I think `scope` and `[]` is not necessary, but the segment of `type:#issue` is more intuitive  for reading the commits .
You can open a new PR  of the commit-guideline to improve the experience for contributing and collaboration
