### ISSUE TITLE
目录简介

### ISSUE THREAD

**Issue by 2892931976** [lindb/lindb#145]
可以说说项目的目录结构吗？正想学习一下。最好能说明每个目录代码的作用或简介

**Comment by stone1100** [comment]
嗯，后续我们加到Contributing的描述里面

**Comment by ghsobetter** [comment]
> 可以说说项目的目录结构吗？正想学习一下。最好能说明每个目录代码的作用或简介

同学学习的如何了

**Comment by CodingCrush** [comment]
目录简介可参考这个链接： 
https://lindb.io/zh/docs/community/contributor-guide.html
