### ISSUE TITLE
Undefined: syscall.Flock

### ISSUE THREAD

**Issue by MrKingHH** [lindb/lindb#157]
I want to run this project, but i encounter some problems. 
![image](https://user-images.githubusercontent.com/22386359/62917292-492b5500-bdce-11e9-9076-3e31d1f107e7.png)
![image](https://user-images.githubusercontent.com/22386359/62917270-2dc04a00-bdce-11e9-8c41-aa9a8a49e4c9.png)
so I have a question, does the lindb support windows? @stone1100 @CodingCrush @damnever @LBinin

**Comment by MrKingHH** [comment]
Look forward to your reply.

**Comment by damnever** [comment]
I suppose Windows is currently not supported by lindb. You may submit a PR or create a separated issue for this.

/cc @stone1100 @CodingCrush

**Comment by MrKingHH** [comment]
I will create another issue to resolve this problem.
