### ISSUE TITLE
build 之前 clean_build把web/build目录删除了

### ISSUE THREAD

**Issue by weisd** [lindb/lindb#159]
https://github.com/lindb/lindb/blob/0a73ea89fcc67efa0b07cebda0edd60e0422a168/Makefile#L18
如题
是不是不应该删除啊

**Comment by stone1100** [comment]
为了让CI跑的快一点，临时把build-frontend去了，后面我们调整一下整个makefile的结构

**Comment by weisd** [comment]
https://github.com/lindb/lindb/blob/a5f59478d8035e39a268fe98e5f14c6bf9047257/broker/api/router.go#L64
这个判断在dockerfile里也没有添加这个目录
rice embed-go 也没有写在makefile里
