### ISSUE TITLE
cors不用写content-type

### ISSUE THREAD

**Issue by weisd** [lindb/lindb#164]
https://github.com/lindb/lindb/blob/1638986fef214eefdae6a7bad3ce1bf6b6d88c59/broker/api/router.go#L81

api的OK，Error已经写了content-type了，这里统一写了的话，static会显示 不了

**Comment by stone1100** [comment]
嗯，也欢迎给我们提PR

**Comment by weisd** [comment]
好的，最近在看代码，感觉好多都没有写完

**Comment by stone1100** [comment]
是的，之前所有的组件都是通过UT来完成的，现在正在做各个组件之间的集成

**Comment by weisd** [comment]
有时间表什么时候出一个release版本吗

**Comment by weisd** [comment]
建个qq群或者slack频道吧

**Comment by stone1100** [comment]
争取最近一个月内出一个alpha版本，交流群后续建到会放到readme上

**Comment by stone1100** [comment]
fix #16
