### ISSUE TITLE
replication 问题

### ISSUE THREAD

**Issue by jacky1193610322** [lindb/lindb#239]
如果副本起来比较晚，也就是wal已经删除过一次，那么这时候前面丢失的数据，按照文档来说，就无法复制过来了，文档中只是复制从wal之后的数据，那么这样的话，如果发生leader切换，岂不是会发生数据丢失。饿了么内部也是这样实现吗？

**Comment by XiaTianliang** [comment]
两个问题，1. wal删除的时机，一般leader会等数据完全同步到replicator后再删除wal，如果遇到极端情况，replicator长时间没有起来，leader wal占用磁盘空间太大，有两个选择，拒绝写入直到磁盘剩余空间足够大，或删除较老的wal，考虑到时序数据的使用场景，可用性比一致性更重要，选择的第二种，允许少量的数据不一致，保证整体的可用。
2. leader切换是否会丢数据，文档中的复制通道是双向的，leader切换不会丢数据，例如有1、2、3三个节点，会同时存在1->2, 1->3, 2->1, 2->3, 3->1, 3->2的六个复制通道，假如开始1为leader，主要的数据复制方向为1->2,1->3,如果切换为2为leader，切换后主要的复制方向为2->1,2->3, 1为leader未复制完的数据还会继续向2、3复制，这和常规的基于有序日志保证主副完全一致的存储(例如raft)实现有差别，对于时序数据，日志的重放的顺序不重要，只要保证日志最终都在节点上重放就可保证节点上的数据是一致的。

**Comment by jacky1193610322** [comment]
谢谢回复，问题没有表述清楚
因为是删除较老的wal，所以如果此时副本开始复制，因为之前的wal已经被删除了，并没有复制，所以这个副本会少一部分数据(如果允许运行一段时间增加副本，那么这个副本丢失的数据会更多，或者是副本重启的过程中，主副本正好删除了wal，这两种都会少数据)，但是当这个副本追上最新的主，会加入isr，如果此时主重启或者宕机，那么刚才哪个副本成为leader，那么会造成缺少数据，少多少数据，取决于这个副本当时起来的时候wal被删除了多少。

**Comment by XiaTianliang** [comment]
内部使用时还没有遇到需要增加或迁移副本的场景，节点会宕机，由于磁盘做了rad，还没有遇到数据无法恢复的情况。如果需要支持这个功能，需要将存储的snapshot发送到其他节点，这个功能目前没有考虑做。

**Comment by jacky1193610322** [comment]
好的，谢谢

**Comment by jacky1193610322** [comment]
再多问一下，在内部使用时，比如出现副本维护过程中，如果主上面的wal被删除了，等副本再起来的时候，那么此时就会丢一部分数据，这种情况出现的概率高吗

**Comment by stone1100** [comment]
> 再多问一下，在内部使用时，比如出现副本维护过程中，如果主上面的wal被删除了，等副本再起来的时候，那么此时就会丢一部分数据，这种情况出现的概率高吗

- 做过副本的runtime增加，如10->20，这个过程基本是无损对用户透明，也不会产生数据的balance，lindb的设计是数据可以散在任意的shard上(正常情况还是写属于自己的leader)，新的数据会按新的shard数来sharding，查询的时候再把数据聚合起来；
- 也经常遇到机器不可用的情况，一般分2情况情况，磁盘上的数据还可用，这时找一个机器替换，把老数据copy过来，再启动，但这时新机器不会成为leader，只有追平了才会有机会再选为leader，另外一种是机器完全不可用，这时新的机器不会被选为leader，在控制面上临时从isr列表中去了，等运行一段时间新数据追平了再手动介入，这种情况没有发生过，一般都是第一种情况；
- WAL删除一般不会导致数据的丢失，因为WAL中会记录ack的位置，只有WAL长期不能复制导致磁盘满了，会丢无法复制的replica数据，但是只要还有一个replica可用，对用户还是可用的，这时应该及时处理这样的问题，目前生产没有遇到某个shard的所有replica都不可用的情况，不过系统已经实现了当某个shard完全不可用的时候，数据会分配给别的shard，类似缩容，更扩容类似，数据还是会在查询的时候聚合成最终的结果；
- 选Leader的时候，也会优先选数据比较全的replica成为leader，以保证查询到的数据是比较全的；

LinDB主要一个场景是监控，系统的可靠性要优于数据的一致性，所以我们的做法是数据最终一致。

**Comment by jacky1193610322** [comment]
好的 谢谢
