### ISSUE TITLE
并发写入和查询能力大概是什么样的，是否具备动态扩容的能力

### ISSUE THREAD

**Issue by nustee** [lindb/lindb#255]
如果有测试报告就最好了

**Comment by stone1100** [comment]
- 可以参考一个这个文章 https://zhuanlan.zhihu.com/p/35998778 下面有一个Java版本报告，Go 版本之前简单能了几个 case 应该跟 java 差不多，个别会好于 Java 版本，等集成测试完之后，后面会有一个详细的测试报告。
- 可以通过动态扩 shard 的方式来对集群进行扩容
