### ISSUE TITLE
Error API request path in web

### ISSUE THREAD

**Issue by shaneing** [lindb/lindb#405]
I run web in localhost, but the API request path starts with `localhost:3000`. For example:

```
http://localhost:3000/cluster/master
```

Expected as follows:

```
http://localhost:9000/cluster/master
```

**Comment by stone1100** [comment]
currently can't start web console work alone, 
you can run lindb as standalone mode(https://github.com/lindb/lindb#standalone-mode)

**Comment by stone1100** [comment]
if run web in localhost for dev/test, need modify api path in 
https://github.com/lindb/lindb/blob/develop/web/src/config/config.ts  

it dep on lindb server.
