### ISSUE TITLE
时序数据集中存储功能

### ISSUE THREAD

**Issue by xewn** [lindb/lindb#412]
用户场景：

1. 一个集团下属20个工厂

2. 每个工厂内有wonderware historian存储实时数据

3. 集团要求将关键数据实时提交到私有云进行存储

4. 每个工厂可能不只有一种时序数据库，可能存在多种时序数据库的情况，比如PI

针对用户的这种场景，如何实现，由工厂向集团的私有云实时推送数据？
让工厂的时序数据库适配LinDB的数据接收，还是实现本地的数据中转，然后提交给LinDB?

**Comment by stone1100** [comment]
可以考虑用一个消息队列，以后也可以适配多少时序数据库
