### ISSUE TITLE
计划什么时候发布版本呢？

### ISSUE THREAD

**Issue by cnpk** [lindb/lindb#413]
我也是比较关注这个项目，希望能够看到一款国产的优秀时序数据库，从以前饿了么提到LinDB就一直在关注。
看最近没有新的代码提交了，会不会停了呢？
希望能够持续完善，谢谢。
以往我使用PI和wonderware比较多一些。

**Comment by stone1100** [comment]
最近别的事情比较多，不会停的

**Comment by cnpk** [comment]
谢谢！

**Comment by jacky1193610322** [comment]
有最新计划吗? 感觉lindb的架构和内部设计非常棒，主要是go版的， 如果是java版的就参与贡献了。

**Comment by cjhui2020** [comment]
现在这个是lindb 3.0吗？还是开源的直到2.0？

**Comment by stone1100** [comment]
https://github.com/lindb/lindb/releases
