### ISSUE TITLE
代码报错，

### ISSUE THREAD

**Issue by smileclound** [lindb/lindb#470]
func (s *shard) createMemoryDatabase() (memdb.MemoryDatabase, error) {
	return newMemoryDBFunc(memdb.MemoryDatabaseCfg{
		Name:     s.databaseName,
		Interval: s.interval,
		Metadata: s.metadata,
		TempPath: filepath.Join(s.path, filepath.Join(tempDir, fmt.Sprintf("%d", timeutil.Now()))),
	})
}

Interval应该为FamilyTime吧

**Comment by smileclound** [comment]
我提交一下

**Comment by stone1100** [comment]
family time是根据interval动态算出来的

把报错贴一下
