### ISSUE TITLE
登陆报404

### ISSUE THREAD

**Issue by piplive** [lindb/lindb#497]
登陆报404; curl 'http://localhost:9000/api/v1/login'   -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2' --compressed  --data-raw '{"username":"admin","password":"admin123"}'

**Comment by CodingCrush** [comment]
暂时不需要登录，因此未注册登录接口
