### ISSUE TITLE
[Feature]支持FirstField和LastField取第一个和最后一个

### ISSUE THREAD

**Issue by letian0805** [lindb/lindb#617]
支持FirstField和LastField取第一个和最后一个

**Comment by stone1100** [comment]
目前基于写入的有序性支持了last，在发布的时候也把first这个类型加上

**Comment by letian0805** [comment]
> 

请问有微信群么？我们这边海量时序数据存储，对读和写性能要求很高，测试了多种时序数据库都不满足要求。看了LinDB的特性和架构，感觉很适合我们的业务场景。想深入了解下

**Comment by stone1100** [comment]
@letian0805 目前已经支持了first/last field
