### ISSUE TITLE
请问是否有计划支持更高精度的时间

### ISSUE THREAD

**Issue by letian0805** [lindb/lindb#618]
我们正在计划用时序数据库存时序的业务数据，调研了很多方案发现LinDB除了时间精度不够外，其他都满足要求。如果时间精度能支持更高，就完美了

**Comment by stone1100** [comment]
大概是怎么样一个精度

**Comment by letian0805** [comment]
> 大概是怎么样一个精度

@stone1100 微秒级别。或者跟influxdb对齐，支持纳秒

**Comment by letian0805** [comment]
请问有没有微信群呢？方便沟通

**Comment by stone1100** [comment]
> 

目前没有微信群，微信群不大好加入。

**Comment by stone1100** [comment]
> 

应该不会支持这样的精度，lindb还是聚焦在时序指标存储，微秒/纳秒就有点像event/log了
