### ISSUE TITLE
请问如何向库中插入数据？

### ISSUE THREAD

**Issue by bigdatabody** [lindb/lindb#734]
找遍了相关文档，好像没有介绍如何插入数据，能否提供个简单的案例分享下，谢谢！另外，web控制台好像只支持少量的sql语句，cil客户端也同样的问题。

**Comment by stone1100** [comment]
正在整理这块的文档，一些写入数据的基本操作后面要抽象到client中，web中已经把一些sql ui化了, cli应该已经支持了除state以外的主要sql

**Comment by bigdatabody** [comment]
能否协助下基本的数据插入、查询操作，我想和toas、InfluxDB等库做下对比测试，谢谢！

**Comment by bigdatabody** [comment]
另外问下lindb不支持字符串存储？

**Comment by stone1100** [comment]
> 能否协助下基本的数据插入、查询操作，我想和toas、InfluxDB等库做下对比测试，谢谢！
这里有一个例子，不过是偏底层一点的。
https://github.com/lindb/lindb/blob/main/e2e/benchmark/write_metric_test.go
下面是各协议写入的例子也可以参考一下：
https://github.com/lindb/lindb/tree/main/app/broker/api/ingest

**Comment by stone1100** [comment]
> 另外问下lindb不支持字符串存储？

不支持string field

**Comment by stone1100** [comment]
use new go client write data: https://github.com/lindb/client_go
