### ISSUE TITLE
Is it Production ready today?

### ISSUE THREAD

**Issue by rebootcode** [lindb/lindb#95]
If not, is there any ETA?

**Comment by CodingCrush** [comment]
We are trying to release a Pre-Alpha version at the end of this month, a stable version will be released at next month.

**Comment by skyrocknroll** [comment]
@CodingCrush Any updated timeline fort 1st release ?

**Comment by stone1100** [comment]
- Release: https://github.com/lindb/lindb/releases
- For installation guides, please check out [Quick start](https://lindb.io/guide/get-started.html) .
