### ISSUE TITLE
[bug]: go get github.com/lindb/client_go 运行报错

### ISSUE THREAD

**Issue by calmatery** [lindb/lindb#957]
**Describe the bug**
执行后，无法正确引用

**Expected behavior** (Required)
go get github.com/lindb/client_go    
go: downloading github.com/lindb/client_go v0.0.2
go: github.com/lindb/client_go: create zip: .github/ISSUE_TEMPLATE/🐛-bug-report.md: malformed file path ".github/ISSUE_TEMPLATE/🐛-bug-report.md": invalid char '🐛'
.github/ISSUE_TEMPLATE/🚀-enhancement.md: malformed file path ".github/ISSUE_TEMPLATE/🚀-enhancement.md": invalid char '🚀'
.github/ISSUE_TEMPLATE/🚀-feature-request.md: malformed file path ".github/ISSUE_TEMPLATE/🚀-feature-request.md": invalid char '🚀'
.github/ISSUE_TEMPLATE/🤔-ask-a-question.md: malformed file path ".github/ISSUE_TEMPLATE/🤔-ask-a-question.md": invalid char '🤔'

**What's your LinDB version?** (Required)
只是引入client，还没有执行连接

**Screenshots**
![image](https://user-images.githubusercontent.com/3176523/230423125-0656b037-8aee-4578-9cca-56ceac751d3f.png)

go version: 1.19.4

**Comment by stone1100** [comment]
可能是包括了emoji导致的，已经去了，需要加一个版本再更新一下看看

go get -u github.com/lindb/client_go@v0.0.2
