### ISSUE TITLE
[question]: Is this a product exchange group?

### ISSUE THREAD

**Issue by auula** [lindb/lindb#987]
Is there an exchange group for the product? WeChat group or other channels of communication group?

**Comment by auula** [comment]
Is there an exchange group for the product? WeChat group or other channels of communication group? I would like to do a technical discussion about the product, thanks.

**Comment by kevin6025** [comment]
Can add WeChat (yuyuss1100)

**Comment by stone1100** [comment]
Can add WeChat (yuyuss1100)

**Comment by auula** [comment]
> Can add WeChat (yuyuss1100)

thank.
