### ISSUE TITLE
[bug]:When the query result is empty, the client will report a null pointer exception.

### ISSUE THREAD

**Issue by joyant** [lindb/lindb#991]
**Describe the bug**
When the query result is empty, the client will report a null pointer exception.

**To Reproduce** (Required)
You can execute this statement to reproduce the bug:
```
show metrics; // executed without any metric
show fields from a; // executed without any metric
```

**Expected behavior** (Required)
It clearly reminds me that the thing I am querying does not exist.

**What's your LinDB version?** (Required)
latest.

**Screenshots**
![screenshot-20231117-175133](https://github.com/lindb/lindb/assets/38974731/c6521351-ecee-44b3-bda9-9ba78475f407)
![screenshot-20231117-175425](https://github.com/lindb/lindb/assets/38974731/cb2a0727-848d-4d60-9db6-fec3620e92bd)

**Additional context**
In addition to showing the error, the above screenshot also shows the comparison of the color of the input SQL statement. You can see that dark blue is not a very good choice. In fact, when I use lindcli for a long time, I feel that my eyes are not comfortable. When I change the color after switching to white, everything was fine, so I also want to change the color of the input sql to white.

**Comment by joyant** [comment]
I can fix this bug, but before fixing it, I hope we can reach a consensus. 

The root cause of this bug is caused by the m.Values.([]interface{}) assertion in the `github.com/lindb/common/models/metadata.go` file, but I prefer to fix it in the ExecuteAsResult function of the `github.com/lindb/internal/client/execute.go` file. The solution is to assert the formatter and determine whether Values is nil, if it is empty, a friendly prompt will be output. 

At the same time, I also want to add the recover method at the top of the ExecuteAsResult method to prevent lindcli from crashing.

In addition, can I change the color of the input sql text?

**Comment by stone1100** [comment]
The root cause is getting zero results from the server when no data is found, this bug can be fixed according to your solution. Can recover at the top of cli execute method then return error message.

Or return an empty result not nil if there is no data, it can make api/cli to return empty.
https://github.com/lindb/lindb/blob/main/query/search.go#L163-L216

**Comment by stone1100** [comment]
Currently some common query cases are supported in LinDB cli.
