### ISSUE TITLE
[enhance]: create database by with statement

### ISSUE THREAD

**Issue by kevin6025** [lindb/lindb#995]
**Please describe enhancement**
create database schema by with statement not json.

like:
create database apm with (shards=2,replica=3.....)

**Comment by joyant** [comment]
I would like to inquire if the mentioned issue has already been initiated. If not, please assign it to me and provide the completed syntax, especially regarding the syntax for options. @stone1100

**Comment by stone1100** [comment]
I do some research. You can ref to https://github.com/antlr/grammars-v4/blob/master/sql/trino/TrinoParser.g4.

Create database schema includes two config options:
1. database config props;
2. database rollup config;

Example: 
`
create database apm 
with(
   shard:1,
   replica:2,
   .....
)
rollup (
  (interval:1h,ttl:1m),
  (interval:1d,ttl:1y)
)
`
